version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: supermarket-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: supermarketdb
    ports:
      - "3307:3306"